import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'first-contribution',
    {
      type: 'category',
      label: 'Set up',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Set up',
        description:
          'Shared toolchain setup for both products. Install Podman or Docker, Task, and the uyuni-docs-builder container. Optional: local tools, WSL2, and VS Code.',
        slug: '/category/deployment-and-installation',
      },
      items: [
        'Uyuni-MLM-toolchain/Deployment-and-Installation/documentation-container',
        'Uyuni-MLM-toolchain/Deployment-and-Installation/local-toolchain-setup',
        'Uyuni-MLM-toolchain/Deployment-and-Installation/Set-Up-WSL2-for-Documentation-Development',
        'Visual-Code-and-Extensions/install-and-configure-visual-studio-code',
      ],
    },
    {
      type: 'category',
      label: 'Build and publish',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Build and publish',
        description:
          'Shared config.yml first, then the product you are shipping. Multi-Linux Manager is enterprise (documentation.suse.com). Uyuni is the open-source community site (uyuni-project.org).',
        slug: '/category/building-and-publishing',
      },
      items: [
        'Uyuni-MLM-toolchain/Building-and-publishing/config-yml',
        {
          type: 'category',
          label: 'Multi-Linux Manager (enterprise)',
          collapsed: false,
          customProps: {icon: '/img/mlm-logo.svg'},
          link: {
            type: 'generated-index',
            title: 'Multi-Linux Manager (enterprise)',
            description:
              'Enterprise documentation for SUSE Multi-Linux Manager. Package English RPMs and publish to documentation.suse.com. Translations for manager-5.1 and manager-5.2 are AI-generated pull requests against those branches.',
            slug: '/category/mlm',
          },
          items: [
            'Uyuni-MLM-toolchain/Building-and-publishing/mlm/packaging-mlm',
            'Uyuni-MLM-toolchain/Building-and-publishing/mlm/publish-mlm-dsc',
          ],
        },
        {
          type: 'category',
          label: 'Uyuni (community)',
          collapsed: false,
          customProps: {icon: '/img/uyuni-logo.png'},
          link: {
            type: 'generated-index',
            title: 'Uyuni (community)',
            description:
              'Open-source community documentation. Package English RPMs on src.opensuse.org, then publish to uyuni-project.org.',
            slug: '/category/uyuni',
          },
          items: [
            'Uyuni-MLM-toolchain/Building-and-publishing/uyuni/packaging-uyuni',
            'Uyuni-MLM-toolchain/Building-and-publishing/uyuni/publish-uyuni',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Tools',
        description:
          'AsciiDoc, Antora, Task, the container, and the other tools we use to write and build the docs.',
        slug: '/category/toolchain',
      },
      items: [{type: 'autogenerated', dirName: 'toolchain'}],
    },
  ],
};

export default sidebars;
