import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manual sidebar to ensure intro appears first, then autogenerate the rest
  tutorialSidebar: [
    'intro',
    'first-contribution',
    'search-help',
    {
      type: 'category', 
      label: 'Uyuni documentation toolchain',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'Uyuni-MLM-toolchain'}],
    },
    {
      type: 'category',
      label: 'Visual Studio Code and extensions',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'Visual-Code-and-Extensions'}],
    },
    {
      type: 'category',
      label: 'Documentation process',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'Documentation-process'}],
    },
  ],
};

export default sidebars;
